//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 12:04:59 PM PDT 
//


package com.solutionset.lq.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getMbrAccountDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="database_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="appl_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="user_token" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="external_tran_id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="getMbrAccountDetails_input">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="member_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="lang_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="element_list">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ytd_nights" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="ytd_base_points" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="ytd_bonus_points" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="ytd_points_redeemed" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="ytd_other_points" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getMbrAccountDetails"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElement(required = true)
    protected Request.GetMbrAccountDetails getMbrAccountDetails;

    /**
     * Gets the value of the getMbrAccountDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Request.GetMbrAccountDetails }
     *     
     */
    public Request.GetMbrAccountDetails getGetMbrAccountDetails() {
        return getMbrAccountDetails;
    }

    /**
     * Sets the value of the getMbrAccountDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request.GetMbrAccountDetails }
     *     
     */
    public void setGetMbrAccountDetails(Request.GetMbrAccountDetails value) {
        this.getMbrAccountDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="database_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="appl_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="user_token" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="external_tran_id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="getMbrAccountDetails_input">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="member_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="lang_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="element_list">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ytd_nights" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="ytd_base_points" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="ytd_bonus_points" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="ytd_points_redeemed" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="ytd_other_points" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "databaseId",
        "applId",
        "username",
        "password",
        "userToken",
        "externalTranId",
        "getMbrAccountDetailsInput",
        "elementList"
    })
    public static class GetMbrAccountDetails {

        @XmlElement(name = "database_id", required = true)
        protected String databaseId;
        @XmlElement(name = "appl_id", required = true)
        protected String applId;
        @XmlSchemaType(name = "unsignedInt")
        protected long username;
        @XmlSchemaType(name = "unsignedShort")
        protected int password;
        @XmlElement(name = "user_token", required = true)
        protected Object userToken;
        @XmlElement(name = "external_tran_id", required = true)
        protected Object externalTranId;
        @XmlElement(name = "getMbrAccountDetails_input", required = true)
        protected Request.GetMbrAccountDetails.GetMbrAccountDetailsInput getMbrAccountDetailsInput;
        @XmlElement(name = "element_list", required = true)
        protected Request.GetMbrAccountDetails.ElementList elementList;

        /**
         * Gets the value of the databaseId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatabaseId() {
            return databaseId;
        }

        /**
         * Sets the value of the databaseId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatabaseId(String value) {
            this.databaseId = value;
        }

        /**
         * Gets the value of the applId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApplId() {
            return applId;
        }

        /**
         * Sets the value of the applId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApplId(String value) {
            this.applId = value;
        }

        /**
         * Gets the value of the username property.
         * 
         */
        public long getUsername() {
            return username;
        }

        /**
         * Sets the value of the username property.
         * 
         */
        public void setUsername(long value) {
            this.username = value;
        }

        /**
         * Gets the value of the password property.
         * 
         */
        public int getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         */
        public void setPassword(int value) {
            this.password = value;
        }

        /**
         * Gets the value of the userToken property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getUserToken() {
            return userToken;
        }

        /**
         * Sets the value of the userToken property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setUserToken(Object value) {
            this.userToken = value;
        }

        /**
         * Gets the value of the externalTranId property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getExternalTranId() {
            return externalTranId;
        }

        /**
         * Sets the value of the externalTranId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setExternalTranId(Object value) {
            this.externalTranId = value;
        }

        /**
         * Gets the value of the getMbrAccountDetailsInput property.
         * 
         * @return
         *     possible object is
         *     {@link Request.GetMbrAccountDetails.GetMbrAccountDetailsInput }
         *     
         */
        public Request.GetMbrAccountDetails.GetMbrAccountDetailsInput getGetMbrAccountDetailsInput() {
            return getMbrAccountDetailsInput;
        }

        /**
         * Sets the value of the getMbrAccountDetailsInput property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.GetMbrAccountDetails.GetMbrAccountDetailsInput }
         *     
         */
        public void setGetMbrAccountDetailsInput(Request.GetMbrAccountDetails.GetMbrAccountDetailsInput value) {
            this.getMbrAccountDetailsInput = value;
        }

        /**
         * Gets the value of the elementList property.
         * 
         * @return
         *     possible object is
         *     {@link Request.GetMbrAccountDetails.ElementList }
         *     
         */
        public Request.GetMbrAccountDetails.ElementList getElementList() {
            return elementList;
        }

        /**
         * Sets the value of the elementList property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.GetMbrAccountDetails.ElementList }
         *     
         */
        public void setElementList(Request.GetMbrAccountDetails.ElementList value) {
            this.elementList = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ytd_nights" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="ytd_base_points" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="ytd_bonus_points" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="ytd_points_redeemed" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="ytd_other_points" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ytdNights",
            "ytdBasePoints",
            "ytdBonusPoints",
            "ytdPointsRedeemed",
            "ytdOtherPoints"
        })
        public static class ElementList {

            @XmlElement(name = "ytd_nights", required = true)
            protected Object ytdNights;
            @XmlElement(name = "ytd_base_points", required = true)
            protected Object ytdBasePoints;
            @XmlElement(name = "ytd_bonus_points", required = true)
            protected Object ytdBonusPoints;
            @XmlElement(name = "ytd_points_redeemed", required = true)
            protected Object ytdPointsRedeemed;
            @XmlElement(name = "ytd_other_points", required = true)
            protected Object ytdOtherPoints;

            /**
             * Gets the value of the ytdNights property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getYtdNights() {
                return ytdNights;
            }

            /**
             * Sets the value of the ytdNights property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setYtdNights(Object value) {
                this.ytdNights = value;
            }

            /**
             * Gets the value of the ytdBasePoints property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getYtdBasePoints() {
                return ytdBasePoints;
            }

            /**
             * Sets the value of the ytdBasePoints property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setYtdBasePoints(Object value) {
                this.ytdBasePoints = value;
            }

            /**
             * Gets the value of the ytdBonusPoints property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getYtdBonusPoints() {
                return ytdBonusPoints;
            }

            /**
             * Sets the value of the ytdBonusPoints property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setYtdBonusPoints(Object value) {
                this.ytdBonusPoints = value;
            }

            /**
             * Gets the value of the ytdPointsRedeemed property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getYtdPointsRedeemed() {
                return ytdPointsRedeemed;
            }

            /**
             * Sets the value of the ytdPointsRedeemed property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setYtdPointsRedeemed(Object value) {
                this.ytdPointsRedeemed = value;
            }

            /**
             * Gets the value of the ytdOtherPoints property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getYtdOtherPoints() {
                return ytdOtherPoints;
            }

            /**
             * Sets the value of the ytdOtherPoints property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setYtdOtherPoints(Object value) {
                this.ytdOtherPoints = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="member_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="lang_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "memberId",
            "langCode"
        })
        public static class GetMbrAccountDetailsInput {

            @XmlElement(name = "member_id", required = true)
            protected String memberId;
            @XmlElement(name = "lang_code", required = true)
            protected String langCode;

            /**
             * Gets the value of the memberId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberId() {
                return memberId;
            }

            /**
             * Sets the value of the memberId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberId(String value) {
                this.memberId = value;
            }

            /**
             * Gets the value of the langCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLangCode() {
                return langCode;
            }

            /**
             * Sets the value of the langCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLangCode(String value) {
                this.langCode = value;
            }

        }

    }

}
